# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform ntfy installation tasks
  block:
    - name: Validate ntfy configuration
      when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install ntfy
      when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - name: Set up ntfy users
    - when:
        - ntfy_enabled | bool
        - ntfy_credentials | length > 0
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_users.yml"
  tags:
    - setup-all
    - setup-ntfy
    - install-all
    - install-ntfy

- name: Perform ntfy uninstallation tasks
  block:
    - name: Uninstall ntfy
      when: not ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-ntfy

- name: Perform ntfy self-check tasks
  block:
    - name: Run self-check for ntfy
      when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
  tags:
    - self-check
