# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - when:
        - ntfy_enabled | bool
        - ntfy_credentials | length > 0
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_users.yml"

  tags:
    - setup-all
    - setup-ntfy
    - install-all
    - install-ntfy

- block:
    - when: not ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-ntfy

- block:
    - when: ntfy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
  tags:
    - self-check
